export { AnalistaComponent } from "./analista/AnalistaComponent";
export { ClientComponent } from "./cliente/ClientComponent";
export { EmpleadoComponent } from "./empleado/EmpleadoComponent";
export { FooterComponent } from "./FooterComponent";
export { ItemNav } from "./ItemNav"
export { LoginComponent } from "./login/LoginComponent";
export { MainComponent } from "./MainComponent";
export { NavComponent } from "./NavComponent";
export { OficinistaComponent } from "./oficinista/OficinistaComponent";
